### ISSUE TITLE
Release a new version with the latest changes

### ISSUE THREAD

**Issue by jeslat** [patrickfav/under-the-hood#3]
Hi, could you release a new version with the latest changes related to the `allowBackup`? Thanks

**Comment by patrickfav** [comment]
Hi, i will release a new version today (MEZ). You can subscribe to the bintray artifact to get the notification.

**Comment by patrickfav** [comment]
Released in https://bintray.com/patrickfav/maven/hood/0.5.2

**Comment by jeslat** [comment]
Thank you
